// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33ce6Ny6rNaEcZjZn8KNDnYhyBRh_6iQ',
    appId: '1:810901848963:web:54fda2f8b2d5baad34ecb6',
    messagingSenderId: '810901848963',
    projectId: 'penguin-store-b4a7e',
    authDomain: 'penguin-store-b4a7e.firebaseapp.com',
    storageBucket: 'penguin-store-b4a7e.firebasestorage.app',
    measurementId: 'G-CVRSGC2ZNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfkZqIfyHuVABfEbCF-6AgKKORbaSTpg',
    appId: '1:810901848963:android:c1dd50f848712cb034ecb6',
    messagingSenderId: '810901848963',
    projectId: 'penguin-store-b4a7e',
    storageBucket: 'penguin-store-b4a7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Klitiw4h_L-iKZ_pq7QmZpsJeKTsXWw',
    appId: '1:810901848963:ios:f6a00cea8f3cd9d634ecb6',
    messagingSenderId: '810901848963',
    projectId: 'penguin-store-b4a7e',
    storageBucket: 'penguin-store-b4a7e.firebasestorage.app',
    iosBundleId: 'com.example.penguinStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Klitiw4h_L-iKZ_pq7QmZpsJeKTsXWw',
    appId: '1:810901848963:ios:f6a00cea8f3cd9d634ecb6',
    messagingSenderId: '810901848963',
    projectId: 'penguin-store-b4a7e',
    storageBucket: 'penguin-store-b4a7e.firebasestorage.app',
    iosBundleId: 'com.example.penguinStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA33ce6Ny6rNaEcZjZn8KNDnYhyBRh_6iQ',
    appId: '1:810901848963:web:5d3e94f9365d2db034ecb6',
    messagingSenderId: '810901848963',
    projectId: 'penguin-store-b4a7e',
    authDomain: 'penguin-store-b4a7e.firebaseapp.com',
    storageBucket: 'penguin-store-b4a7e.firebasestorage.app',
    measurementId: 'G-WJZERMB65S',
  );
}
